"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
hop = [
  "bookmark",
  "move",
  "--from",
  "closest_bookmark(@)",
  "--to",
  "closest_pushable(@)",
]
l = ["log"]
n = ["new"]
ol = ["op", "log"]

[git]
sign-on-push = true
write-change-id-header = true

[signing]
behavior = "drop"
backend = "gpg"

[ui]
default-command = "log"
diff-editor = ":builtin"
graph.style = "square"
log-synthetic-elided-nodes = true
pager = "less -FRX"

[user]
name = "Luc Perkins"
email = "lucperkins@gmail.com"
