"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
hop = [
  "bookmark",
  "move",
  "--from",
  "closest_bookmark(@)",
  "--to",
  "closest_pushable(@)",
]
init = ["git", "init", "--colocate"]

[git]
sign-on-push = true
write-change-id-header = true

[revset-aliases]
"T" = "trunk()"
"trunk()" = "main@origin"

[signing]
behavior = "drop"
backend = "gpg"

[ui]
default-command = "log"
diff-editor = ":builtin"
graph.style = "square"
log-synthetic-elided-nodes = true

[user]
name = "Luc Perkins"
email = "lucperkins@gmail.com"
